[package]
name = "MoveToTsTestsuite"
version = "0.0.1"

[dependencies]
Econia = { git = "https://github.com/econia-labs/econia.git", subdir = "src/move/econia", rev = "711cb00e05b13ca03498b7f413ac21e65a8cc027" }
hippo-swap = { git = "https://github.com/hippospace/hippo-swap.git", rev = "545bd487849c769701982daf381ea12c0b6132ac" }

[addresses]
MoveToTsTestsuite = "0x12345"


